### ISSUE TITLE
Error due to /controller_manager on launching the axebot.launch.py file

### ISSUE THREAD

**Issue by aamodbk** [mateusmenezes95/axebot#2]
I have followed the guide given in the repository README to install all required dependencies on the foxy version of the package and even for omnidirectional_controller I have installed the foxy version specifically as I am running it on a Ubuntu 22.04 machine. The build works fine and compiles as expected and all dependencies get installed too but an error shows up on using the command `ros2 launch axebot_gazebo axebot.launch.py` to launch the file.

![Screenshot from 2023-12-16 08-02-49](https://github.com/mateusmenezes95/axebot/assets/77502673/923036d2-9735-4ed3-ba93-f9ff9f04b4ec)

```
[spawner.py-6] [INFO] [1702742523.966068594] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-5] [INFO] [1702742524.011552589] [spawner_omnidirectional_controller]: Waiting for /controller_manager services
[gzserver-3] Segmentation fault (core dumped)
[ERROR] [gzserver-3]: process has died [pid 9958, exit code 139, cmd 'gzserver                                                                       -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].
[spawner.py-6] [INFO] [1702742525.974316086] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-5] [INFO] [1702742526.019569104] [spawner_omnidirectional_controller]: Waiting for /controller_manager services
[spawner.py-6] [INFO] [1702742527.982664827] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-5] [INFO] [1702742528.026907060] [spawner_omnidirectional_controller]: Waiting for /controller_manager services
[spawner.py-6] [INFO] [1702742529.990337206] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-5] [INFO] [1702742530.035777912] [spawner_omnidirectional_controller]: Waiting for /controller_manager services
[spawner.py-6] [INFO] [1702742531.998107961] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-5] [INFO] [1702742532.043160764] [spawner_omnidirectional_controller]: Waiting for /controller_manager services
[spawner.py-6] [ERROR] [1702742534.006244248] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner.py-6]: process has died [pid 10043, exit code 1, cmd '/opt/ros/foxy/lib/controller_manager/spawner.py joint_state_broadcaster --ros-args'].
[spawner.py-5] [ERROR] [1702742534.050925254] [spawner_omnidirectional_controller]: Controller manager not available
[ERROR] [spawner.py-5]: process has died [pid 10041, exit code 1, cmd '/opt/ros/foxy/lib/controller_manager/spawner.py omnidirectional_controller --ros-args'].
```

It doesn't seem to be able to load the controllers. I have installed all dependencies of ros2_control like ros-foxy-ros2-control and ros-foxy-ros2-controllers. Please help me identifying the issue.

**Comment by aamodbk** [comment]
@mateusmenezes95 could you please help out in resolving this?

**Comment by aamodbk** [comment]
Hello @mateusmenezes95 , I have managed to resolve the above issue mentioned but I am facing another error regarding the working of the omnidirectional_controller package. When I launch the `axebot.launch.py` file, I face an error as follows:
```
[gzserver-3] [ERROR] [1702835784.192216812] [omnidirectional_controller]: Unable to obtain joint state handle for wheel1_joint
[gzserver-3] [WARN] [1702835784.192263942] [omnidirectional_controller]: Error occurred while doing error handling.
[gzserver-3] [ERROR] [1702835784.192298093] [controller_manager]: After activation, controller 'omnidirectional_controller' is in state 'unconfigured' (1), expected 'active' (3).
```
It would be very helpful if you could give a solution to this.

**Comment by mateusmenezes95** [comment]
Hello @aamodbk. Just to make sure that we are facing a bug... Did you checkout the omnidirectional_controllers repository to the foxy branch? I am asking because by default the clone happens with the humble branch there

**Comment by aamodbk** [comment]
Hello @mateusmenezes95, The problem was resolved on its own. I would like to think it had something to do with the ROS2 versions but I made almost no changes and it started working so I do not exactly know what was causing the issue. It had something to do with the gazebo ros2 default controller_manager not starting but it is resolved now. Thank you for your attention.

**Comment by CosimaDorland** [comment]
Hello @mateusmenezes95 
I loaded the whole axebot system on humble, using the humble version in axebot/axebot.foxy.repos instead of foxy, and am getting exactly the same error as @aamodbk. Here is my error : 

`[gzserver-3] [INFO] [1704724238.342368811] [controller_manager]: Configuring controller 'omnidirectional_controller'`
`[spawner-6] [INFO] [1704724238.466758645] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster`
`[gzserver-3] [INFO] [1704724238.658969124] [controller_manager]: Configuring controller 'joint_state_broadcaster'`
`[gzserver-3] [INFO] [1704724238.660412408] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published`
`[gzserver-3] [ERROR] [1704724239.299151749] [omnidirectional_controller]: Unable to obtain joint state handle for wheel1_joint`
`[gzserver-3] [WARN] [1704724239.299415568] [omnidirectional_controller]: Error occurred while doing error handling.`
`[gzserver-3] [ERROR] [1704724239.299517688] [controller_manager]: After activation, controller 'omnidirectional_controller' is in state 'unconfigured' (1), expected 'active' (3).`
`[spawner-5] [INFO] [1704724239.601585864] [spawner_omnidirectional_controller]: Configured and activated omnidirectional_controller`
`[INFO] [spawner-5]: process has finished cleanly [pid 61869]`
`[INFO] [rviz2-7]: process started with pid [61961]`

Please could you help with this if possible

**Comment by mateusmenezes95** [comment]
Hello @CosimaDorland. It is the same problem reported in https://github.com/mateusmenezes95/axebot/issues/4. I am going to take a look soon

**Comment by mateusmenezes95** [comment]
@CosimaDorland, take a look in my comment in https://github.com/mateusmenezes95/axebot/issues/4
